### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by rafaellop** [omaxlive/com.omarben.inappreview#3]
Please include information that the SKStoreReviewController cannot be displayed from app distributed throught TestFlight. I've had my headache when trying to find out what's going on.... Here's doc info from:
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

> When you call this method while your app is still in development mode, a rating/review request view is always displayed so that you can test the user interface and experience. However, this method has no effect when you call it in an app that you distribute using TestFlight.

**Comment by omaxlive** [comment]
Hi @rafaellop it's included now to the documentation. Thank you!
